ALTER TABLE grupos
ADD COLUMN IF NOT EXISTS tem_caucao BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS valor_caucao NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS fidelidade_meses INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS servico_personalizado_nome TEXT;
